spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-zs-dev
---
spring:
  profiles: test #测试环境
  application: microservicecloud-config-zs-test
  
 #必须保存为UTF-8格式