spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201

spring:
  profiles:
    active: dev
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defauletZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202

spring:
  profiles:
    active: test
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defauletZone: http://eureka-test.com:7001/eureka/